apiVersion: v1
kind: Pod
metadata:
  name: secretpod
spec:
  containers:
  - name: secretpod
    image: busybox
    args:
    - sleep
    - "1000000"    
    volumeMounts:
    - name: kvdemo
      mountPath: /etc/mysql-password
  volumes:
  - name: kvdemo
        flexVolume:
          driver: "azure/kv"
          options:
            usevmmanagedidentity: "true"       
            vmmanagedidentityclientid: "<CLIENTID>"     
            keyvaultname: "<NAMEOFKEYVALUT>"       
            keyvaultobjectnames: "KEYVAULTOBJECT"
            keyvaultobjecttypes: secret               
            tenantid: "<AZUREADTENANTID>"  